[ServerMonitoring]
other = "服务器"

[Server]
other = "主机"

[Services]
other = "服务"

[Task]
other = "任务"

[Notification]
other = "报警"

[Settings]
other = "设置"

[Home]
other = "首页"

[BackToHomepage]
other = "返回前台"

[AdminPanel]
other = "管理后台"

[Logout]
other = "注销登录"

[Login]
other = "登录"

[ConfirmLogout]
other = "确认注销？"

[AfterLoggingOutYouHaveToLoginAgain]
other = "注销后您必须重新登录才能使用"

[Cancel]
other = "取消"

[Confirm]
other = "确认"

[AddScheduledTasks]
other = "添加计划任务"

[Name]
other = "名称"

[Scheduler]
other = "计划"

[BackUp]
other = "备份"

[3amDaily]
other = "(每天3点)"

[Command]
other = "命令"

[Coverage]
other = "覆盖范围"

[IgnoreAllAndExecuteOnlyThroughSpecificServers]
other = "忽略所有，仅通过特定服务器执行"

[AllIncludedOnlySpecificServersAreNotExecuted]
other = "覆盖所有，仅特定服务器不执行"

[SpecificServers]
other = "特定服务器"

[EnterIdAndNameToSearch]
other = "输入ID/名称以搜索"

[NotificationMethodGroup]
other = "通知方式组"

[PushSuccessMessages]
other = "推送成功的消息"

[TheFormaOfTheScheduleIs]
other = "计划的格式为："

[SecondsMinutesHoursDaysMonthsWeeksSeeDetails]
other = "秒 分 时 天 月 星期，详情见"

[ScheduleExpressionFormat]
other = "计划表达式格式"

[IntroductionOfCommands]
other = "命令：就像写 shell/bat 脚本一样，但是不推荐换行，多个命令使用 <code>&&</code>/<code>&</code> 连接，如果遇到 xxx 命令找不到，可能是<code>PATH</code> 环境变量的问题，<code>Linux</code> 主机在命令开头加入<code>source ~/.bashrc</code>或者使用绝对路径执行。"

[AddMonitor]
other = "添加监测项"

[Blog]
other = "博客"

[Target]
other = "目标"

[Type]
other = "类型"

[SslExpirationOrChange]
other = "(SSL到期、变更)"

[Duration]
other = "请求间隔"

[Seconds]
other = "秒"

[EnableFailureNotification]
other = "启用故障通知"

[IntroductionOfMonitor]
other = """
类型为 <b>HTTP-GET</b> 时输入URL(带 http/https, HTTPS协议的会顺带监控SSL证书)；<br>
类型为 <b>ICMP-Ping</b> 时输入主机名/IP，不带端口；<br>
类型为 <b>TCP-Ping</b> 时输入主机名/IP + 端口号：example.com:22"""

[AddNotificationMethod]
other = "添加通知方式"

[Tag]
other = "分组"

[DoNotSendTestMessages]
other = "不发送测试信息"

[RequestMethod]
other = "请求方式"

[RequestType]
other = "请求类型"

[VerifySSL]
other = "验证SSL"

[AddNotificationRule]
other = "添加报警规则"

[Rules]
other = "规则"

[Enable]
other = "启用"

[AddServer]
other = "添加服务器"

[ServerGroup]
other = "服务器分组"

[EinsteinLightspeed1]
other = "北京"

[DisplayIndex]
other = "排序"

[TheLargerTheNumberTheHigherThePriority]
other = "越大越靠前"

[Secret]
other = "密钥"

[Note]
other = "备注"

[LinuxOneKeyInstall]
other = "Linux 一键安装"

[NoDomainAlert]
other = "请先在设置页面配置 后端探针配置"

[PushSuccessfully]
other = "成功推送"

[LastExecution]
other = "最后执行"

[LastResult]
other = "最后结果"

[Administration]
other = "管理"

[CoverAll]
other = "覆盖所有"

[IgnoreAll]
other = "忽略所有"

[DeleteScheduledTask]
other = "删除计划任务"

[ConfirmToDeleteThisScheduledTask]
other = "确认删除此计划任务？"

[AccessDenied]
other = "访问受限"

[Use]
other = "使用"

[AccountToLogin]
other = "账号登录"

[SignUp]
other = "注册"

[DontHaveAnAccount]
other = "没有账号？"

[SSLCertificate]
other = "HTTP(S)/SSL证书"

[TCPPort]
other = "TCP 端口"

[DeleteService]
other = "删除服务"

[ConfirmToDeleteThisService]
other = "确认删除此服务？"

[DeleteNotificationMethod]
other = "删除通知方式"

[ConfirmToDeleteThisNotificationMethod]
other = "确认删除此通知方式？"

[DeleteNotificationRule]
other = "删除报警规则"

[ConfirmToDeleteThisNotificationRule]
other = "确认删除此报警规则？"

[ForceUpdate]
other = "强制更新"

[SelectAll]
other = "全选"

[VersionNumber]
other = "版本号"

[OneKeyInstall]
other = "一键安装"

[ClickToCopyTheInstallationCommand]
other = "点击复制安装命令"

[DeleteServer]
other = "删除主机"

[ConfirmToDeleteThisServer]
other = "确认删除此主机？"

[NoServerSelected]
other = "当前没有选中的服务器"

[ExecutionResults]
other = "执行结果"

[SiteTitle]
other = "站点标题"

[AdministratorList]
other = "管理员列表"

[Theme]
other = "主题"

[CustomCodes]
other = "自定义代码(style、script 都可以)"

[AccessPassword]
other = "前台查看密码"

[AgentConfig]
other = "后端探针配置"

[AgentDomainOrIP]
other = "后端探针指向的域名或IP"

[AgentPort]
other = "后端探针指向的端口"

[IPChangeAlert]
other = "IP 变更提醒"

[AllIncludedOnlySpecificServersAreNotAlerted]
other = "覆盖所有，仅特定服务器不提醒"

[IgnoreAllOnlyAlertSpecificServers]
other = "忽略所有，仅提醒特定服务器"

[IgnoreAllRequestOnlyThroughSpecificServers]
other = "忽略所有，仅通过特定服务器请求"

[AllIncludedOnlySpecificServersAreNotRequest]
other = "覆盖所有，仅特定服务器不请求"

[ServerIDSeparatedByCommas]
other = "服务器 ID 以逗号隔开"

[IPChangeNotificationTag]
other = "提醒发送至指定的通知分组"

[NotificationMessagesDoNotHideIP]
other = "通知信息 IP 不打码"

[Save]
other = "保存"

[ModifiedSuccessfully]
other = "修改成功"

[TerminalConnectionTimeOutOrSessionEnded]
other = "Terminal 连接超时或会话已结束"

[TerminalConnectionFailed]
other = "Terminal 连接失败，请检查 /terminal/* 的 WebSocket 反代情况"

[Default]
other = "默认"

[Offline]
other = "已离线"

[Platform]
other = "架构"

[DiskUsed]
other = "硬盘"

[MemUsed]
other = "内存"

[SwapUsed]
other = "交换"

[NetTransfer]
other = "流量"

[Load]
other = "负载"

[ProcessCount]
other = "进程"

[ConnCount]
other = "连接"

[BootTime]
other = "启动"

[LastActive]
other = "活动"

[Version]
other = "版本"

[NetSpeed]
other = "网络"

[Uptime]
other = "在线"

[ServerIsOffline]
other = "节点已离线"

[Day]
other = "天"

[RealtimeChannelEstablished]
other = "实时通道建立"

[GetTheLatestMonitoringDataInRealTime]
other = "可以实时获取最新监控数据啦"

[RealtimeChannelDisconnect]
other = "实时通道断开"

[CanNotGetTheLatestMonitoringDataInRealTime]
other = "无法实时获取最新监控数据咯"

[30DaysOnline]
other = "30天在线率"

[Details]
other = "详情"

[Status]
other = "状态"

[Availability]
other = "在线率"

[AverageLatency]
other = "平均延迟"

[CycleTransferStats]
other = "流量统计"

[From]
other = "自"

[To]
other = "至"

[NextCheck]
other = "下次检查"

[CurrentUsage]
other = "当前用量"

[VerifyPassword]
other = "验证查看密码"

[LightMode]
other = "白昼模式"

[DarkMode]
other = "暗黑模式"

[GridLayout]
other = "网格视图"

[ListLayout]
other = "列表视图"

[EnterPassword]
other = "输入密码"

[Location]
other = "地区"

[Running]
other = "运行中"

[UpNetTransfer]
other = "上行"

[DownNetTransfer]
other = "下行"

[TotalUpNetTransfer]
other = "总上行"

[TotalDownNetTransfer]
other = "总下行"

[WrongPassword]
other = "密码错误"

[AnErrorEccurred]
other = "出现错误"

[SystemError]
other = "系统错误"

[NetworkError]
other = "网络错误"

[ServicesStatus]
other = "服务状态"

[ServersManagement]
other = "服务器管理"

[ServicesManagement]
other = "服务监控"

[ScheduledTasks]
other = "计划任务"

[ApiManagement]
other="API"

[IssueNewApiToken]
other="添加密钥"

[APIToken]
other="API 密钥"

[Token]
other="密钥"

[DeleteToken]
other="删除密钥"

[ConfirmToDeleteThisToken]
other="确认删除密钥？"

[YouAreNotAuthorized]
other = "此页面需要登录"

[WrongAccessPassword]
other = "查看密码错误"

[Add]
other = "添加"

[Edit]
other = "修改"

[AlarmRule]
other = "报警规则"

[NotificationMethod]
other = "通知方式"

[Incident]
other = "故障"

[Resolved]
other = "恢复"

[StatusDown]
other = "故障"

[StatusNoData]
other = "无数据"

[StatusGood]
other = "良好"

[StatusLowAvailability]
other = "低可用"

[ScheduledTaskExecutedSuccessfully]
other = "任务成功"

[ScheduledTaskExecutedFailed]
other = "任务失败"

[IPAddress]
other = "IP 地址"

[IPChanged]
other = "IP 变更"

[Notify]
other = "探针通知"

[OldIP]
other = "旧 IP："

[NewIP]
other = "新 IP："

[Rule]
other = "规则："

[TaskServer]
other = "服务器："

[TaskLog]
other = "日志："

[Traffic]
other = "流量"

[Transleft]
other = "流量剩余"