version: "3.3"

services:
  dashboard:
    image: image_url
    restart: always
    volumes:
      - ./data:/dashboard/data
      - ./theme-custom/template:/dashboard/resource/template/theme-custom:ro
      - ./theme-custom/static:/dashboard/resource/static/theme-custom:ro
      - ./dashboard-custom/template:/dashboard/resource/template/dashboard-custom:ro
      - ./dashboard-custom/static:/dashboard/resource/static/dashboard-custom:ro
    ports:
      - site_port:site_port
      - grpc_port:grpc_port